on: push
jobs:
  job1:
    name: Ubuntu Test
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        uses: actions/checkout@v2
      - name : Step 2
        run: echo "Print the Date"

  job2:
    name: MacOS Test
    runs-on: macos-latest
    steps:
      - name: Step 1
        uses: actions/checkout@v2
      - name : Step 2
        run: echo "Print the Date"

  job3:
    name: Windows Test
    runs-on: windows-latest
    steps:
      - name: Step 1
        uses: actions/checkout@v2
      - name : Step 2
        run: echo "Print the Date"

  job4:
    name: Final Test
    needs: [job1, job2, job3]
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        uses: actions/checkout@v2
      - name : Step 2
        run: echo "env"
