on: push 
env:
  APP_NAME: Deepali
jobs:
   test:
     name: Test the app 
     runs-on: ubuntu-latest
     steps:
      - name: Running Test 
        run : Py hello.py 
      - uses: actions/checkout@v2
   build:
     name: Build the app
     needs: [test]
     runs-on: ubuntu-latest
     steps:
      - name: Deployed
        uses: actions/Upload-artifact@v1
        with:
          name: linux
          path: .
        
        
